### ISSUE TITLE
 opencv-python>=3.  ERROR: Failed building wheel for gym  

### ISSUE THREAD

**Issue by 942411526** [NVIDIA-Omniverse/Orbit#150]
version 2023.1.0
setuptools==66

The above exception was the direct cause of the following exception:
      
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-qlm4aeyy/gym_1d715195577e468eb9faccfaff96f6de/setup.py", line 39, in <module>
          setup(
        File "/home/yx/anaconda3/envs/orbit/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/home/yx/anaconda3/envs/orbit/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
        File "/home/yx/anaconda3/envs/orbit/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/yx/anaconda3/envs/orbit/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/yx/anaconda3/envs/orbit/lib/python3.10/site-packages/setuptools/dist.py", line 1208, in run_command
          super().run_command(command)
        File "/home/yx/anaconda3/envs/orbit/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/yx/anaconda3/envs/orbit/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 416, in run
          self.egg2dist(self.egginfo_dir, distinfo_dir)
        File "/home/yx/anaconda3/envs/orbit/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 559, in egg2dist
          pkg_info = pkginfo_to_metadata(egginfo_path, pkginfo_path)
        File "/home/yx/anaconda3/envs/orbit/lib/python3.10/site-packages/wheel/metadata.py", line 160, in pkginfo_to_metadata
          for key, value in generate_requirements({extra: reqs}):
        File "/home/yx/anaconda3/envs/orbit/lib/python3.10/site-packages/wheel/metadata.py", line 138, in generate_requirements
          for new_req in convert_requirements(depends):
        File "/home/yx/anaconda3/envs/orbit/lib/python3.10/site-packages/wheel/metadata.py", line 103, in convert_requirements
          parsed_requirement = Requirement(req)
        File "/home/yx/anaconda3/envs/orbit/lib/python3.10/site-packages/wheel/vendored/packaging/requirements.py", line 37, in __init__
          raise InvalidRequirement(str(e)) from e
      wheel.vendored.packaging.requirements.InvalidRequirement: Expected end or semicolon (after version specifier)
          opencv-python>=3.
                       ~~~^
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for gym
  Running setup.py clean for gym
  Building wheel for robomimic (setup.py) ... done
  Created wheel for robomimic: filename=robomimic-0.3.0-py3-none-any.whl size=256880 sha256=0361f09104eb61b8b71633253238eabd92e9707484c64843b34853a7f219ad75
  Stored in directory: /tmp/pip-ephem-wheel-cache-bp0v_k3f/wheels/dd/27/74/dd3391055b5b7e7a388a85ea8f1ed0789b060a29e769095024
  Building wheel for rsl_rl (pyproject.toml) ... done
  Created wheel for rsl_rl: filename=rsl_rl-2.0.1-py3-none-any.whl size=21522 sha256=d608957552b7c5d4ef35f3111e09704de4ed47dbeeecac98fbf8971524325c04
  Stored in directory: /tmp/pip-ephem-wheel-cache-bp0v_k3f/wheels/df/84/8f/920bf23a80cb154988e98981536fd76d6acc067b64a806070a
Successfully built robomimic rsl_rl
Failed to build gym
ERROR: Could not build wheels for gym, which is required to install pyproject.toml-based projects

**Comment by Amin-Azar** [comment]
@942411526 I am facing exact same problem. How did you resolve this please?
