### ISSUE TITLE
[Bug Report] Attribute error in `play_ray_caster_camera.py`

### ISSUE THREAD

**Issue by btx0424** [NVIDIA-Omniverse/Orbit#154]
It looks like when running with `--headless` the initialization of `RayCasterCamera` is not properly triggered.

### Steps to reproduce

Running `python play_ray_caster_camera.py --num_envs 4 --headless` using the latest commit of `devel` gives
```
...
[INFO] Generating terrains based on curriculum took : 0.132799 seconds
2023-12-01 03:45:39 [69,566ms] [Error] [__main__] 'RayCasterCamera' object has no attribute '_device'
2023-12-01 03:45:39 [69,567ms] [Error] [__main__] Traceback (most recent call last):
  File ".../isaac_ws/Orbit/source/standalone/demo/play_ray_caster_camera.py", line 172, in <module>
    main()
  File ".../isaac_ws/Orbit/source/standalone/demo/play_ray_caster_camera.py", line 110, in main
    camera.set_world_poses_from_view(eyes + terrain.env_origins, targets + terrain.env_origins)
  File ".../isaac_ws/Orbit/source/extensions/omni.isaac.orbit/omni/isaac/orbit/sensors/ray_caster/ray_caster_camera.py", line 218, in set_world_poses_from_view
    orientations = math_utils.quat_from_matrix(create_rotation_matrix_from_view(eyes, targets, device=self._device))
AttributeError: 'RayCasterCamera' object has no attribute '_device'
```

### Checklist

- [x] I have checked that there is no similar issue in the repo (**required**)
- [x] I have checked that the issue is not in running Isaac Sim itself and is related to the repo

**Comment by Mayankm96** [comment]
Thanks for pointing it out. We made a small fix for it in: f98eebceaf1e694e69ab0306b804d0fbb62b9393
