### ISSUE TITLE
[Bug Report] did not specify filter keys corresponding to train and valid split in dataset -- immitation learning example

### ISSUE THREAD

**Issue by Amin-Azar** [NVIDIA-Omniverse/Orbit#163]
While running the train script
``./orbit.sh -p source/standalone/workflows/robomimic/tools/split_train_val.py logs/robomimic/Isaac-Lift-Franka-v0/hdf_dataset.hdf5 --ratio 0.2

``

I got the following error:

```
run failed with error:
did not specify filter keys corresponding to train and valid split in dataset - please fill config.train.hdf5_filter_key and config.train.hdf5_validation_filter_key

Traceback (most recent call last):
  File "source/standalone/workflows/robomimic/train.py", line 360, in main
    train(config, device=device)
  File "source/standalone/workflows/robomimic/train.py", line 145, in train
    trainset, validset = TrainUtils.load_data_for_training(config, obs_keys=shape_meta["all_obs_keys"])
  File "/home/fabrisight/anaconda3/envs/orbit2/lib/python3.7/site-packages/robomimic/utils/train_utils.py", line 107, in load_data_for_training
    "did not specify filter keys corresponding to train and valid split in dataset" \
AssertionError: did not specify filter keys corresponding to train and valid split in dataset - please fill config.train.hdf5_filter_key and config.train.hdf5_validation_filter_key
```

- Isaac Sim Version: 2022.2.0
- OS: Ubuntu 22.04

**Comment by Amin-Azar** [comment]
as per https://robomimic.github.io/docs/datasets/overview.html, I added the following code in the ``source/standalone/workflows/robomimic/train.py`` file at line 350:

```
#Updated with filter_keys as per https://robomimic.github.io/docs/datasets/overview.html
    config.train.hdf5_filter_key="train"
    config.train.hdf5_validation_filter_key="valid"
```
