### ISSUE TITLE
ModuleNotFoundError: No module named 'rsl_rl'  When running existing examples

### ISSUE THREAD

**Issue by SantiDiazC** [NVIDIA-Omniverse/orbit#286]
Hi, thanks for your great work!
I recently reinstall orbit with the newest version of isaac sim (2023.1.1) and the installation went ok. I can run the "showroom" examples,
however, when I run 'list_envs.py' or any other like 'zero_agent.py', 'random_agent.py' or any of the followers I have the following error:
```error
[8.283s] Simulation App Startup Complete
[8.343s] [ext: omni.kit.stagerecorder.core-105.0.4] startup
Traceback (most recent call last):
  File "/home/hri-david/Omniverse/Orbit/source/standalone/environments/zero_agent.py", line 40, in <module>
    import omni.isaac.orbit_tasks  # noqa: F401
  File "/home/hri-david/Omniverse/Orbit/source/extensions/omni.isaac.orbit_tasks/omni/isaac/orbit_tasks/__init__.py", line 30, in <module>
    import_packages(__name__, _BLACKLIST_PKGS)
  File "/home/hri-david/Omniverse/Orbit/source/extensions/omni.isaac.orbit_tasks/omni/isaac/orbit_tasks/utils/importer.py", line 40, in import_packages
    for _ in _walk_packages(package.__path__, package.__name__ + ".", blacklist_pkgs=blacklist_pkgs):
  File "/home/hri-david/Omniverse/Orbit/source/extensions/omni.isaac.orbit_tasks/omni/isaac/orbit_tasks/utils/importer.py", line 87, in _walk_packages
    yield from _walk_packages(path, info.name + ".", onerror, blacklist_pkgs)
  File "/home/hri-david/Omniverse/Orbit/source/extensions/omni.isaac.orbit_tasks/omni/isaac/orbit_tasks/utils/importer.py", line 75, in _walk_packages
    __import__(info.name)
  File "/home/hri-david/Omniverse/Orbit/source/extensions/omni.isaac.orbit_tasks/omni/isaac/orbit_tasks/classic/ant/__init__.py", line 12, in <module>
    from . import agents, ant_env_cfg
  File "/home/hri-david/Omniverse/Orbit/source/extensions/omni.isaac.orbit_tasks/omni/isaac/orbit_tasks/classic/ant/agents/__init__.py", line 6, in <module>
    from . import rsl_rl_ppo_cfg
  File "/home/hri-david/Omniverse/Orbit/source/extensions/omni.isaac.orbit_tasks/omni/isaac/orbit_tasks/classic/ant/agents/rsl_rl_ppo_cfg.py", line 8, in <module>
    from omni.isaac.orbit_tasks.utils.wrappers.rsl_rl import (
  File "/home/hri-david/Omniverse/Orbit/source/extensions/omni.isaac.orbit_tasks/omni/isaac/orbit_tasks/utils/wrappers/rsl_rl/__init__.py", line 10, in <module>
    from .vecenv_wrapper import RslRlVecEnvWrapper
  File "/home/hri-david/Omniverse/Orbit/source/extensions/omni.isaac.orbit_tasks/omni/isaac/orbit_tasks/utils/wrappers/rsl_rl/vecenv_wrapper.py", line 23, in <module>
    from rsl_rl.env import VecEnv
ModuleNotFoundError: No module named 'rsl_rl'
```
Is there any solution  for this? I am new to orbit so I don't know if I need to do additional process to install rsl_rl module.

Thank you in advance!

**Comment by SantiDiazC** [comment]
Forgot to run:
./orbit.sh --extras rsl_rl

Sorry about that
